
tags:
  name: Users
  description: User management endpoints

/api/users/register:
  post:
    summary: Register a new user
    tags: [Users]
    requestBody:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              username:
                type: string
              password:
                type: string
            required:
              - username
              - password
    responses:
      201:
        description: User registered successfully
      400:
        description: User already exists
      500:
        description: Internal server error


/api/users/login:
  post:
    summary: Log in a user and generate a JWT token
    tags: [Users]
    requestBody:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              username:
                type: string
              password:
                type: string
            required:
              - username
              - password
    responses:
      200:
        description: JWT token generated successfully
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
      401:
        description: Invalid credentials
      500:
        description: Internal server error


/api/users/logout:
  post:
    summary: Log out a user
    tags: [Users]
    responses:
      200:
        description: User logged out
      500:
        description: Internal server error